export const product = [
    // Celulares Google
    {
        id: 1,
        stock: 15,
        marca: "Google",
        title: "Google Pixel 8",
        img: "",
        description: "Smartphone con excelente cámara y un diseño innovador. Incluye el potente chip Tensor.",
        price: 699,
        category: "Celular",
    },
    {
        id: 2,
        stock: 20,
        marca: "Google",
        title: "Google Pixel 8 Pro",
        img: "",
        description: "La versión premium del Pixel 8, ideal para fotógrafos y profesionales.",
        price: 999,
        category: "Celular",
    },
    {
        id: 3,
        stock: 12,
        marca: "Google",
        title: "Google Pixel 7a",
        img: "",
        description: "Rendimiento sobresaliente y excelente relación calidad-precio.",
        price: 499,
        category: "Celular",
    },
    {
        id: 4,
        stock: 8,
        marca: "Google",
        title: "Google Pixel Fold",
        img: "",
        description: "El primer plegable de Google, combina productividad y estilo.",
        price: 1799,
        category: "Celular",
    },

    // Celulares Apple
    {
        id: 5,
        stock: 10,
        marca: "Apple",
        title: "iPhone 15",
        img: "",
        description: "El último modelo de iPhone, con mejor batería y rendimiento.",
        price: 899,
        category: "Celular",
    },
    {
        id: 6,
        stock: 8,
        marca: "Apple",
        title: "iPhone 15 Pro Max",
        img: "",
        description: "El iPhone más avanzado, diseñado para quienes buscan lo mejor.",
        price: 1299,
        category: "Celular",
    },
    {
        id: 7,
        stock: 12,
        marca: "Apple",
        title: "iPhone SE (3ra generación)",
        img: "",
        description: "Compacto, potente y más asequible.",
        price: 429,
        category: "Celular",
    },
    {
        id: 8,
        stock: 5,
        marca: "Apple",
        title: "iPhone 14 Plus",
        img: "",
        description: "Pantalla más grande y mejor batería en un diseño clásico.",
        price: 999,
        category: "Celular",
    },

    // Celulares Samsung
    {
        id: 9,
        stock: 15,
        marca: "Samsung",
        title: "Samsung Galaxy S23",
        img: "",
        description: "El equilibrio perfecto entre innovación y funcionalidad.",
        price: 799,
        category: "Celular",
    },
    {
        id: 10,
        stock: 10,
        marca: "Samsung",
        title: "Samsung Galaxy S23 Ultra",
        img: "",
        description: "Máximo rendimiento con un diseño espectacular.",
        price: 1199,
        category: "Celular",
    },
    {
        id: 11,
        stock: 14,
        marca: "Samsung",
        title: "Samsung Galaxy Z Fold 5",
        img: "",
        description: "La última tecnología plegable para usuarios avanzados.",
        price: 1799,
        category: "Celular",
    },
    {
        id: 12,
        stock: 9,
        marca: "Samsung",
        title: "Samsung Galaxy A54",
        img: "",
        description: "Una gran opción a un precio accesible.",
        price: 349,
        category: "Celular",
    },

    // Computadoras Google
    {
        id: 13,
        stock: 5,
        marca: "Google",
        title: "Google Pixelbook Go",
        img: "",
        description: "Ultraligero y perfecto para tareas cotidianas.",
        price: 649,
        category: "Computadora",
    },
    {
        id: 14,
        stock: 4,
        marca: "Google",
        title: "Google Chromebook",
        img: "",
        description: "Rápido, seguro y diseñado para estudiantes y profesionales.",
        price: 299,
        category: "Computadora",
    },

    // Computadoras Apple
    {
        id: 15,
        stock: 6,
        marca: "Apple",
        title: "MacBook Air M2",
        img: "",
        description: "Portátil ultraligera con el poderoso chip M2.",
        price: 999,
        category: "Computadora",
    },
    {
        id: 16,
        stock: 3,
        marca: "Apple",
        title: "MacBook Pro 16\"",
        img: "",
        description: "Diseñada para profesionales, con pantalla grande y excelente rendimiento.",
        price: 2499,
        category: "Computadora",
    },

    // Computadoras Samsung
    {
        id: 17,
        stock: 4,
        marca: "Samsung",
        title: "Samsung Galaxy Book 3 Pro",
        img: "",
        description: "Potencia y portabilidad en un diseño elegante.",
        price: 1299,
        category: "Computadora",
    },
    {
        id: 18,
        stock: 7,
        marca: "Samsung",
        title: "Samsung Chromebook Plus",
        img: "",
        description: "Ideal para quienes buscan un dispositivo práctico y económico.",
        price: 549,
        category: "Computadora",
    },
];
